### ISSUE TITLE
Onnxrt on apple M1

### ISSUE THREAD

**Issue by Cogitarian** [ORB-HD/deface#23]
Daface works find, but slow. I tried to install onnruntime on apple M1 and I can import onnx and onnexruntime in PyCharm, but these libraries are not available when I run DEFACE in terminal. Is there any trick to either run DEFACE in PyCharm or use onnx properly on m1?

**Comment by mdraw** [comment]
Please refer to https://github.com/microsoft/onnxruntime/issues/6633, there are build instructions linked in this thread. Make sure to install and build everything inside a dedicated virtualenv: https://virtualenv.pypa.io/en/latest/user_guide.html
Since this is an onnxruntime issue I'm closing this here.
